spring:
  jpa:
    open-in-view: false
  graphql:
    cors:
      allowed-origins: '*'
      allow-credentials: false
logging:
  level:
    io.netty.channel.AbstractChannel: error

max-page-size: 100
max-buffer-size: 10485760
steam:
  api-key: ${STEAM_API_KEY}
  api-base-url: 'https://api.steampowered.com'
  app-details-url: 'https://store.steampowered.com/api/appdetails'