spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:${DB_PORT}/steam_distillery
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
scheduling:
  enabled: true