spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:steam_distillery
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  graphql:
    graphiql:
      enabled: true